export type { Accommodation, AccommodationCategory } from './Accommodation'
export type { Day } from './Day'
export { FoodVenueCategory } from './FoodVenue'
export type { FoodVenue } from './FoodVenue'
export type { GeoLocation } from './GeoLocation'
export type { Image } from './Image'
export type { PointOfInterest, PointOfInterestCategory } from './PointOfInterest'
export type { ShoppingLocation } from './ShoppingLocation'
export type { Stop, StopTarget, StopTargetType } from './Stop'
export type { Transport, TransportCategory } from './Transport'
export type { Trip } from './Trip'
